### ISSUE TITLE
Backend can return the total User footprint for a MONTH 

### ISSUE THREAD

**Issue by jdcarey128** [Carbon-Knight/carbon-knight-back-end#12]
- [x] Returns the aggregated user footprint across all endpoints (eg. car, flight, etc) for the selected MONTH
- [ ] Data input: ``` { fetchUserMonthFootprint(userID: Int \n month: String){ carbon_in_kg} ```
- [x] Output: ``` { "data": { "fetchUserMonthFootprint": {"carbon_in_kg": Int}}```

**Comment by ETBassist** [comment]
Would this be an extension, since it's an aggregate of multiple footprint categories?
