### ISSUE TITLE
Backend can create a monthly mileage for user

### ISSUE THREAD

**Issue by jdcarey128** [Carbon-Knight/carbon-knight-back-end#7]
- [ ] Data Input 
```
{
car_id: int, 
total_mileage (for month): int, 
month: string, 
year: string 
}
```
- [ ] Define CarMonthlyMileage model callback before_save to make cloverly request with total mileage and car fuel efficiency (mpg and fuel type)
- [ ] Build CloverlyFacade (get_car_footprint)
- [ ] Build CloverlyService (Faraday call to sinatra app; get_car_footprint)
- [ ] Microservice request data: 
```
{    
 total_mileage: Int,
 mpg: Int, 
 fuel_type: String
}
```
- [ ] Mock microservice response JSON for footprint ID 
```
{
  data:
    {
      equivalent_carbon_in_kg: 12.153,
      clover_offset_cost: {
        currency: 'USD',
        total: '0.28'
      }
    }
}
```

**Comment by ETBassist** [comment]
Issues that are part of this:
#11 
#17 
#18
