### ISSUE TITLE
Backend can respond with a footprint for a user YTD

### ISSUE THREAD

**Issue by jdcarey128** [Carbon-Knight/carbon-knight-back-end#9]
- [ ] Returns the aggregated user footprint across all endpoints (eg. car, flight, etc) for the selected year
- [ ] Data input: ``` { fetchUserFootprint(userID: Int \n year: String){ carbon_in_kg} ```
- [ ] Output: ``` { "data": { "fetchUserFootprint": {"carbon_in_kg": Int}}```

**Comment by ETBassist** [comment]
Would something like fetchUserAnnualFootprint be a better name, just for clarities sake?
